"""Clear persisted reason text generated by automatic survey status changes."""

import os

from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv()
database_url = os.getenv("DATABASE_URL")
if not database_url:
    raise SystemExit("DATABASE_URL is not set")

engine = create_engine(database_url, pool_pre_ping=True)
with engine.begin() as connection:
    for table in ("surveys", "survey_assignments"):
        statement = text(
            f"UPDATE {table} "
            "SET captain_status_reason = NULL "
            "WHERE captain_status_reason LIKE 'Auto-cancelled:%' "
            "OR captain_status_reason LIKE 'Auto-rescheduled:%'"
        )
        result = connection.execute(statement)
        remaining = connection.execute(
            text(
                f"SELECT count(*) FROM {table} "
                "WHERE captain_status_reason LIKE :cancelled "
                "OR captain_status_reason LIKE :rescheduled"
            ),
            {
                "cancelled": "Auto-cancelled:%",
                "rescheduled": "Auto-rescheduled:%",
            },
        ).scalar_one()
        print(
            f"{table}: cleared {result.rowcount}; "
            f"{remaining} automatic reasons remain"
        )